name: Deploy Docker Image to Production

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/ss-corpse-chat-utilities:latest
          secrets: |
            "SOCKET_PORT=7200"
            ALLOW_LIST=["https://corpsechat.com","https://www.corpsechat.com"]
      -
        name: Pull & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{ secrets.SSH_HOST }}
            USER_NAME: ${{ secrets.SSH_USER_NAME }}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER_NAME }}@${{ secrets.SSH_HOST }} '
              cd /home/${{ secrets.SSH_USER_NAME }}/code/ss-corpse-chat-utilities &&
              docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} &&
              docker stop socket && docker rm socket &&
              docker image rm ${{ vars.DOCKERHUB_USERNAME }}/ss-corpse-chat-utilities &&
              docker image pull ${{ vars.DOCKERHUB_USERNAME }}/ss-corpse-chat-utilities:latest &&
              docker run -it --name socket --platform linux/amd64 -d -p 8081:7200 ${{ vars.DOCKERHUB_USERNAME }}/ss-corpse-chat-utilities
              '
